ProjetoMVC/MVC_GerenciadorDeConteudo/Controllers/ArquivosController.cs
using Business;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_GerenciadorDeConteudo.Controllers
{
    public class  ArquivosController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Arquivo = new Arquivo().lista();
            return View();
        }
        public ActionResult Novo()
        {
            return View();
        }
        [HttpPost]
        public void Criar()
        {
           
           
            var Arquivo = new Arquivo();
            Arquivo.Titulo = Request["Titulo"];
            Arquivo.Processo = Request["Processo"];
            Arquivo.Categoria = Convert.ToInt32(Request["Categoria"]);


            var files = AddFiles(Request.Files, "Arquivo");

            foreach (var f in files)
            {
                if (f.Key == "Arquivo")
                    Arquivo.Arquivos = f.Value;
            }

            
            Arquivo.save();
            TempData.Add("sucesso", "Dados salvos com sucesso!");
           
            Response.Redirect("/Arquivos");
        }
        public ActionResult Editar(int id)
        {
            var arquivo = Arquivo.BuscaPorId(id);
            ViewBag.Arquivo = arquivo;
            return View();
        }
        [HttpPost]
        public void Alterar(int id)
        {
            try
            {
                var arquivo = Arquivo.BuscaPorId(id);
                DateTime data;
                DateTime.TryParse(Request["data"], out data);
                arquivo.Titulo = Request["Titulo"];
                arquivo.Processo = Request["Processo"];
                arquivo.Categoria = Convert.ToInt32(Request["Categoria"]);

                var files = AddFiles(Request.Files, "Arquivo");

                foreach (var f in files)
                {
                    if (f.Key == "Arquivo")
                       arquivo.Arquivos = f.Value;
                }
                arquivo.save();

                TempData.Add("sucesso", "Dados Actualizada com sucesso!");

            }
            catch(Exception e)
            {
                TempData.Add("erro",e.Message);
            }
            Response.Redirect("/Arquivos");
        }
        public void Excluir(int id)
        {
            
            Arquivo.Excluir(id);

            Response.Redirect("/Arquivos");
        }

        public IDictionary<string, string> AddFiles(HttpFileCollectionBase files, string name)
        {
            try
            {

                IDictionary<string, string> savedFile = new Dictionary<string, string>();

                for (int i = 0; i < files.Count; i++)
                {
                    string fname = "";

                    string path = AppDomain.CurrentDomain.BaseDirectory + "Upload/";
                    string filename = Path.GetFileName(Request.Files[i].FileName);
                    string extension = Path.GetExtension(Request.Files[i].FileName);

                    HttpPostedFileBase file = files[i];

                    if (filename != "")
                    {
                        fname = name + "_" + DateTime.Now.Day.ToString() + "0" + DateTime.Now.Month.ToString() + DateTime.Now.Year.ToString() + "_" + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + "_" + i + DateTime.Now.Millisecond.ToString() + extension;

                        filename = Path.Combine(Server.MapPath("~/Upload/"), fname);
                        file.SaveAs(filename);
                    }
                    savedFile[files.AllKeys[i]] = fname;

                }

                return savedFile;
            }
            catch (Exception e)
            {
                throw;
            }
        }

    }
}

ProjetoMVC/MVC_GerenciadorDeConteudo/Views/Arquivos/Editar.cshtml
@{
    Business.Arquivo arquivo = ViewBag.Arquivo;
}

    <div class="jumbotron">
        <h3>Nova </h3>
        <div>
            <a href="/arquivos" class=" btn btn-default">Voltar</a>
        </div>
        <form action="/Arquivos/@arquivo.Id/alterar" method="post" enctype="multipart/form-data">

            <div class="form-group">
                <label for="arquivo">Titulo:</label>
                <input type="text" class="form-control" value="@arquivo.Titulo" id="titulo" name="titulo" />
            </div>

            <div class="form-group form-check">
                <label for="Processo">Processo:</label>

                <select name="Processo" class="form-control">
                    <option selected>-Selecione--</option>
                    <option value="Admistrativo">Admistrativo</option>
                    <option value="TI">TI</option>
                </select>
            </div>


            <div class="form-group form-check">
                <label for="categoria">Categoria:</label>

                <select name="categoria" class="form-control">
                    <option selected>-Selecione--</option>
                    <option value="1">teste 1</option>
                    <option value="2" selected>teste 2 </option>
                </select>
            </div>

            <div class="form-group">
                <label for="arquivo">Arquivo:</label>

                <input type="file" name="Arquivo" class="form-control rounded-0" id="Arquivo">

            </div>



            <div class="form-group form-check">
                <label for="Ativo">Ativo:</label>
                <input class="form-check-input position-static"   value="@arquivo.Ativo" type="checkbox" id="Ativo" name="Ativo" value="true" aria-label="...">
            </div>

            <button type="submit" class="btn btn-default">Salvar</button>
        </form>
    </div>

ProjetoMVC/MVC_GerenciadorDeConteudo/Views/Arquivos/Index.cshtml
@{
    List<Business.Arquivo> arquivo = ViewBag.Arquivo;
}
@if (TempData["sucesso"] != null)
{
    <div class="alert alert-success">@TempData["sucesso"]</div>
}
@if (TempData["erro"] != null)
{
    <div class="alert alert-danger">@TempData["erro"]</div>
}
<div class="jumbotron">
    <h1>Arquivo</h1>
    <div>
        <a href="/paginas/novo" class=" btn btn-default">Nova arquivo </a>
    </div>
    <table class="table">
        <tr>
            <td>ID</td>
            <td>Titulo</td>
            <td>Arquivos</td>
            <td>Processo</td>
            <td>Categora</td>
            <td></td>
            <td></td>

        </tr>
        @foreach (var p in arquivo)
        {
            <tr>
                <td>@p.Id</td>
                <td>@p.Titulo</td>

                <td><a href="~/Upload/@(p.Arquivos)" target="_blank"><img src="~/Upload/@(p.Arquivos)" alt="" style="height: 23px; width: 56px; object-fit: contain; margin-right: 10px" /><small>Clique para abrir</small></a></td>

                <td>@p.Processo</td>

                <td>@p.NomeCategoria</td>

                <td>
                    <a href="/Arquivos/@p.Id/editar" class=" btn btn-primary"> Alterar dados </a>
                </td>
                <td>
                    <a href="/Arquivos/@p.Id/excluir" class=" btn btn-danger" onclick="ValidaExclusao(@p.Id, event)"> Excluir dados </a>
                </td>

            </tr>
        }
    </table>
</div>

ProjetoMVC/MVC_GerenciadorDeConteudo/Views/Arquivos/Novo.cshtml
<div class="jumbotron">
    <h3>Nova</h3>
    <div>
        <a href="/Arquivos" class=" btn btn-default">Voltar</a>
    </div>

    <form action="/Arquivos/criar" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="arquivo">Titulo:</label>
            <input type="text" class="form-control" id="titulo" name="titulo" />
        </div>

        <div class="form-group form-check">
            <label for="Processo">Processo:</label>

            <select name="Processo" class="form-control">
                <option selected>-Selecione--</option>
                <option value="Admistrativo">Admistrativo</option>
                <option value="TI">TI</option>
            </select>
        </div>


        <div class="form-group form-check">
            <label for="categoria">Categoria:</label>

            <select name="categoria" class="form-control">
                <option selected>-Selecione--</option>
                <option value="1">teste 1</option>
                <option value="2" selected>teste 2 </option>
            </select>
        </div>

        <div class="form-group">
            <label for="arquivo">Arquivo:</label>

            <input type="file" name="Arquivo" class="form-control rounded-0" id="Arquivo">

        </div>



        <div class="form-group form-check">
            <label for="Ativo">Ativo:</label>
            <input class="form-check-input position-static" type="checkbox" id="Ativo" name="Ativo" value="true" aria-label="...">
        </div>

        <button type="submit" class="btn btn-default">Salvar</button>
    </form>

</div>

ProjetoMVC/MVC_GerenciadorDeConteudo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/validacoes.js")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PaginaTeste", "Index", "Arquivos", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Novo", "novo", "Arquivos")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Aplicativo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>